import Head from "next/head";
import { Title } from "@mantine/core";
import TmdbSearch from "@/components/Autocomplete";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Import Muli font */}
        <link rel="stylesheet" href="https://use.typekit.net/gyj5ubh.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title>Home</Title>
      </main>
    </>
  );
}
